Update chatGPT
updated the client according to new models and changes on the APIs

diff --git a/chatGPT b/chatGPT
--- a/chatGPT
+++ b/chatGPT
@@ -6,16 +6,18 @@
 #   -> https://beta.openai.com/account/api-keys
 #
 #
-# chatGPT use 2 parameters: max_token and temperature.
+# chatGPT use 3 parameters: model, max_token and temperature.
+#
+# - model =     select which model to use.
+#               If not specified default is gpt-3.5-turbo.
+#               You can try gpt-4 to ask more complex question/tasks.
 #
 # - max_tokens = the maximum number of tokens to generate in completion.
 #                Default = 4000
-#
-#                1000 tokens =~ 750 words
 #                Your prompt + max_tokens can't exceed the context lenght of the model.
 #
 # - temperature = defines the type of processing applied to answer.
-#                 Default = 0.7
+#                 Default = 0.5
 #
 #                 - lower (e.g. 0.0 / 1.0):
 #                 chatGPT will choose words with a higher probability of occurrence.
@@ -39,8 +41,12 @@ green=$(tput setaf 2)
 TOKEN="" # -> ADD/CHANGE HERE YOUR API TOKEN
 
 
+#defautl model
+MODEL="gpt-3.5-turbo"
+
+
 #default temperature declaration
-TEMP="0.7"
+TEMP="0.5"
 
 
 #default max_tokens declaration
@@ -51,28 +57,30 @@ MAXTOKENS="4000"
 help () {
   echo "${colorreset}\n--------------------"
   echo "\n${red}chatGPT TERMINAL CLIENT${colorreset}"
-  echo "Simple script to query one direct question to chatGPT."
-  echo "\n${green}Usage: ${colorreset}chatGTP [Options] 'Question in single quotes'"
-  echo "\n${green}Example: ${colorreset}chatGPT 'Write a oneliner in powershell to get a reverse shell'"
-  echo "\n${green}Options:${colorreset}"
-  echo "-t or --temperature <0.0-1.0>: set the temperature used."
-  echo "\n     If not specified ${green}default value is 0.7${colorreset}."
+  echo "\nSimple script to query one direct question to chatGPT."
+  echo "\n${green}Usage: ${colorreset}chatGTP -m gpt-4 -t 1.0 -m 1000 'Question in single quotes'"
+  echo "\n${green}Example: ${colorreset}chatGPT 'Write a powershell oneliner to send a command to a server list'"
+  echo "\n${green}Options${colorreset}"
+  echo "\n-m or --model <MODEL>: select the model to use."
+  echo "     If not specified ${green}default value is 'gpt-3.5-turbo'${colorreset}."
+  echo "     You can try 'gpt-4' to ask more complex questions/tasks."
+  echo "\n-t or --temperature <0.0-2.0>: set the temperature used."
+  echo "\n     If not specified ${green}default value is 0.5${colorreset}."
   echo "     ${red}Lower ${colorreset}temperature (e.g. 0.0 / 1.0):"
   echo "     chatGPT will choose words with a higher probability of occurrence."
   echo "     Useful when we want to complete something with the most probable value/phrase/word."
   echo "     ${red}Higher ${colorreset}temperature (e.g. 1.0 / max 2.0):"
   echo "     Very creative but inconsistent answers."
   echo "     Above 1.5 very inconsistent."
-  echo "\n-m or --max-tokens <NUMBER>: the maximum number of tokens to generate in completion."
+  echo "\n-mt or --max-tokens <NUMBER>: the maximum number of tokens to generate in completion."
   echo "\n     If not specified ${green}default value is 4000${colorreset}."
-  echo "     1000 tokens =~ 750 words."
   echo "     Your prompt + max_tokens can't exceed the context lenght of the model."
   echo "\n-h or --help: print this help."
-  echo "\n\n${red}*** Attention ***"
+  echo "\n${red}*** Attention ***"
   echo "${colorreset}You have to ${green}escape ${colorreset}double quotes in questions: e.g. "${green}'\"'
   echo "${colorreset}For ${red}single quote ' ${colorreset}do ${red}NOT ${colorreset}try to escape them."
   echo "Use ${green}backtick \` ${colorreset}instead!"
-  echo "\n\n${colorreset}Cya! \m/"
+  echo "\n${colorreset}Cya! \m/"
   echo "\n--------------------\n"
 }
 
@@ -94,6 +102,30 @@ while test $# -gt 0; do
         -h|--help)
             help
             exit 0
+            ;;
+        -m|--model)
+            shift
+            if test $# -gt 1;then
+                case "$1" in
+                    [gG]*)
+                        export MODEL=$1
+                        ;;
+                    *)
+                        echo "${colorreset}\n--------------------"
+                        echo "\n${red}Invalid model value specified!"
+                        echo "${colorreset}Use -h or --help to view usage examples"
+                        echo "\n--------------------\n"
+                        exit $E_BADARGS
+                        ;;
+                esac
+            else
+                echo "${colorreset}\n--------------------"
+                echo "\n${red}No max-tokens value specified!"
+                echo "${colorreset}Use -h or --help to view usage examples"
+                echo "\n--------------------\n"
+                exit 1
+            fi
+            shift
             ;;
         -t|--temperature)
             shift
@@ -119,7 +151,7 @@ while test $# -gt 0; do
             fi
             shift
             ;;
-        -m|--max-tokens)
+        -mt|--max-tokens)
             shift
             if test $# -gt 1; then
                 case "$1" in
@@ -161,6 +193,7 @@ fi
 #output question, temperature used and max_tokens value.
 echo "${colorreset}\n--------------------"
 echo "${red}\nQuestion: "$1
+echo "${red}Model: "$MODEL
 echo "Temperature: "$TEMP
 echo "Max_tokens: "$MAXTOKENS
 
@@ -173,21 +206,25 @@ echo "${green}\nAnswer:"
 #curl query command
 query=`cat <<EOS
 curl -s https://api.openai.com/v1/chat/completions \
-  -H 'Content-Type: application/json' \
-  -H "Authorization: Bearer $TOKEN" \
-  -d '{
-  "model": "gpt-3.5-turbo",
-  "prompt": "$1",
+  -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" -d '{
+  "model": "$MODEL",
+  "messages": [
+    {
+      "role": "system",
+      "content": "$1"
+    }
+  ],
   "max_tokens": $MAXTOKENS,
   "temperature": $TEMP
-
 }' \
---insecure | jq '.choices[]'.text
-EOS`
+--insecure | jq '.choices[]'.message.content
+##EOS`
 
 
 #execution
-echo ${green}$(eval ${query} | sed '1s/^.//' | sed 's/.$//' | sed 's@\\"@"@g')
+echo ${green}$(eval ${query})
+
+## | sed '1s/^.//' | sed 's/.$//' | sed 's@\\"@"@g')
 
 
 #end
